version: '3.4'

services:
  flask-app:
    volumes: 
      - "/home/stoneisfun/ssd-test:/app"
    environment:
      - FLASK_ENV=Testing
    networks: 
      - selenium_network

networks:
  selenium_network:
    external: true